FROM registry.fedoraproject.org/fedora-minimal:44 as builder

ARG DNF_KEEP_CACHE=false

RUN --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var \
<<EORUN
set -xeuo pipefail

# Packages to install:
# - git, php, php-fpm and required php modules
packages=(
    "git-core"
    "php-cli"
    "php-fpm"
    "/etc/php.d/20-bz2.ini"
    "/etc/php.d/20-calendar.ini"
    "/etc/php.d/20-ctype.ini"
    "/etc/php.d/20-curl.ini"
    "/etc/php.d/20-dom.ini"
    "/etc/php.d/20-exif.ini"
    "/etc/php.d/20-fileinfo.ini"
    "/etc/php.d/20-ftp.ini"
    "/etc/php.d/20-gd.ini"
    "/etc/php.d/20-gettext.ini"
    "/etc/php.d/20-iconv.ini"
    "/etc/php.d/20-intl.ini"
    "/etc/php.d/20-ldap.ini"
    "/etc/php.d/20-mbstring.ini"
    "/etc/php.d/20-pdo.ini"
    "/etc/php.d/20-pgsql.ini"
    "/etc/php.d/20-phar.ini"
    "/etc/php.d/20-posix.ini"
    "/etc/php.d/20-shmop.ini"
    "/etc/php.d/20-simplexml.ini"
    "/etc/php.d/20-soap.ini"
    "/etc/php.d/20-sqlite3.ini"
    "/etc/php.d/20-sysvmsg.ini"
    "/etc/php.d/20-sysvsem.ini"
    "/etc/php.d/20-sysvshm.ini"
    "/etc/php.d/20-tokenizer.ini"
    "/etc/php.d/20-xml.ini"
    "/etc/php.d/20-xmlwriter.ini"
    "/etc/php.d/20-xsl.ini"
    "/etc/php.d/30-mcrypt.ini"
    "/etc/php.d/30-pdo_pgsql.ini"
    "/etc/php.d/30-pdo_sqlite.ini"
    "/etc/php.d/30-xmlreader.ini"
    "/etc/php.d/40-apcu.ini"
    "/etc/php.d/40-zip.ini"
)

# Packages to manually remove after the initial package installation:
# - findutils, grep & sed: ca-certificates deps, not needed after installation
packages_remove=(
    "findutils"
    "grep"
    "sed"
    "dbus"
    "dbus-broker"
    "dbus-common"
    "expat"
    "systemd"
    "systemd-pam"
    "systemd-shared"
    "systemd-sysusers"
)

# List of paths to manually remove after package installation
cleanup=(
)

sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"

if [[ "${DNF_KEEP_CACHE}" == "true" ]]; then
    # For faster local iterations. Must be combined with:
    # --volume "$(pwd)/cache.libdnf5:/output/var/cache/libdnf5:rw,z"
    echo -e "[main]\nkeepcache=True" > "/etc/dnf/libdnf5.conf.d/keepcache.conf"
fi

mkdir -p /output

# Install required packages
dnf install -y \
    --releasever 44 \
    --forcearch "x86_64" \
    --installroot /output \
    --use-host-config \
    --setopt install_weak_deps=False \
    --nodocs \
    fedora-release-container \
    glibc-minimal-langpack \
    "${packages[@]}"

# Additional packages to manually remove after the initial package installation:
# - fedora-gpg-keys & fedora-repos: not needed after installation
packages_remove+=(
    "fedora-gpg-keys"
    "fedora-repos"
)

# Remove packages after installation
rpm --root /output --erase --nodeps --noscripts --notriggers --verbose \
    "${packages_remove[@]}"

# Manual cleanup of a few packages we don't need
# rm -rf /etc/dnf/protected.d/systemd.conf /usr/share/dnf5/libdnf.conf.d/protect-systemd.conf

# List all installed RPMs
rpm -qa --root /output | sort -h

# Remove all SUID/SGID binaries
find /output/usr \( -perm -4000 -o -perm -2000 \) -exec rm -v {} \;

# Disable safe directory check in Git
echo -e "[safe]\n  directory = *" > /output/usr/share/httpd/.gitconfig

# Clean up leftover files from dnf
cleanup+=(
    "/etc/dnf"
    "/run/dnf"
    "/usr/lib/sysimage/libdnf5"
    "/usr/share/dnf5"
)
# Clean up empty docs folders
cleanup+=(
    "/usr/share/doc"
    "/usr/share/info"
    "/usr/share/man"
)
# Clean up other empty folders
cleanup+=(
    "/afs"
    "/boot"
    "/home"
    "/media"
    "/mnt"
    "/opt"
    "/root"
    "/srv"
    "/usr/games"
    "/usr/lib/debug"
    "/usr/lib/games"
    "/usr/lib/modules"
    "/usr/local"
    "/usr/share/X11"
    "/usr/share/augeas"
    "/usr/share/bash-completion"
    "/usr/share/fish"
    "/usr/share/games"
    "/usr/share/gnome"
    "/usr/share/help"
    "/usr/share/ima"
    "/usr/share/modulefiles"
    "/usr/share/pkgconfig"
    "/usr/share/sounds"
    "/usr/share/themes"
    "/usr/share/wayland-sessions"
    "/usr/share/xsessions"
    "/usr/share/zsh"
    "/usr/src"
    "/usr/tmp"
)
# Do the clean up
for p in "${cleanup[@]}"; do
    rm -rv "/output${p}"
done
EORUN

# Rechunk
FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=builder,src=/output,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build --prune /var/cache/libdnf5 \
            > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
USER apache
CMD ["/usr/sbin/php-fpm"]
