FROM registry.fedoraproject.org/fedora-minimal:43 as builder

RUN <<EORUN
set -xeuo pipefail

sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
echo -e "[main]\nkeepcache=True" > "/etc/dnf/libdnf5.conf.d/keepcache.conf"

mkdir -p /output

RELEASEVER="$(. /etc/os-release && echo "${VERSION_ID}")"
ARCH="$(arch)"

# Install nginx and additional modules
dnf install -y \
    --releasever "${RELEASEVER}" \
    --forcearch "${ARCH}" \
    --installroot /output \
    --use-host-config \
    --setopt install_weak_deps=False \
    --nodocs \
    fedora-release-container \
    glibc-minimal-langpack \
    systemd-journal-remote

# Manual cleanup of a few packages we don't need
rpm --root /output --erase --nodeps --noscripts --notriggers --verbose \
    dbus \
    dbus-broker \
    dbus-common \
    expat \
    fedora-gpg-keys \
    fedora-repos \
    libfdisk \
    libseccomp \
    systemd-pam

# List all installed RPMs
rpm -qa --root /output | sort -h

# Remove all SUID/SGID binaries
find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;
EORUN

# Rechunk
FROM quay.io/jlebon/chunkah AS chunkah
RUN --mount=from=builder,src=/output,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
USER 1000:systemd-journal
# CMD ["/usr/sbin/nginx", "-g", "daemon off;error_log /dev/stdout info;"]
